# Generated by Django 5.0.4 on 2024-04-24 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_orderplaced_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='id',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='last_purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='leaderScore',
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
